basic.show_icon(IconNames.HEART)
SuperBit.music(SuperBit.enMusic.FUNK)

def on_forever():
    SuperBit.RGB_Program().show_color(neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.ORANGE))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.YELLOW))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.GREEN))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.BLUE))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.RED))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.INDIGO))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.VIOLET))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
    SuperBit.RGB_Program().set_pixel_color(0, neopixel.colors(NeoPixelColors.WHITE))
    SuperBit.RGB_Program().show()
    basic.pause(1000)
basic.forever(on_forever)
